# Generated by Django 5.2.4 on 2025-08-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_alert", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cryptoselection",
            old_name="price",
            new_name="alert_price",
        ),
        migrations.AddField(
            model_name="cryptoselection",
            name="now_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
