# Generated by Django 5.2.4 on 2025-08-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_alert", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
