# Generated by Django 5.2.4 on 2025-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_alert", "0004_rename_price_cryptoselection_alert_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoselection",
            name="last_checked_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
