# Generated by Django 5.2.4 on 2025-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_alert", "0005_cryptoselection_last_checked_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptoselection",
            name="last_checked_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
