# Generated by Django 5.2.4 on 2025-08-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_alert", "0006_alter_cryptoselection_last_checked_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptoselection",
            name="now_price",
        ),
    ]
