# Generated by Django 5.2.4 on 2025-08-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_alert", "0007_remove_cryptoselection_now_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoselection",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
