# Generated by Django 5.2.4 on 2025-08-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_alert", "0008_cryptoselection_is_expired"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
    ]
