# Generated by Django 5.2.4 on 2025-08-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_alert", "0009_cryptosymbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptosymbol",
            name="name",
        ),
    ]
