# Generated by Django 5.2.4 on 2025-08-15 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_alert", "0010_remove_cryptosymbol_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptoselection",
            name="alert_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Ціна, при досягненні якої сповіщення спрацює.",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="cryptoselection",
            name="crypto",
            field=models.CharField(
                help_text="Символ криптовалюти (наприклад, BTCUSDT).", max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="cryptoselection",
            name="is_expired",
            field=models.BooleanField(
                default=False, help_text="Вказує, чи сповіщення вже спрацювало."
            ),
        ),
        migrations.AlterField(
            model_name="cryptoselection",
            name="last_checked_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Остання перевірена ціна для порівняння з alert_price.",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="cryptoselection",
            name="user",
            field=models.ForeignKey(
                help_text="Користувач, який отримує сповіщення.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
